### ISSUE TITLE
Possible to fix lighting and optimize polygon position?

### ISSUE THREAD

**Issue by leifdenby** [avik-pal/RayTracer.jl#15]
Really nice work. Reading https://avik-pal.github.io/RayTracer.jl/dev/getting_started/inverse_lighting/ I was wondering if the opposite problem of fixing the lighting position and direction, and instead estimate how a fixed number of polygons would be positioned to create the seen image?

The reason I ask is because I'd like to estimate the spatial distribution of cloud water from a number of observations. I would split the scene I'm observing into a fixed number voxels. Based on the amount of water in each voxel a ray would get attenuated and reflected by a known amount. And so the question is to estimate the amount of water in each voxel. Does this make sense?

**Comment by avik-pal** [comment]
Indeed that is possible. However, I am afraid that this codebase is not suitable for it.

I am linking some interesting work which involves estimation of shape of objects from a single view:

1. [Soft Rasterizer: A Differentiable Renderer for Image-based 3D Reasoning](https://arxiv.org/abs/1904.01786)
2. [Differentiable Interpolation Based Renderer](https://nv-tlabs.github.io/DIB-R/)

**Comment by leifdenby** [comment]
Thank you for your suggestions!
