### ISSUE TITLE
Question about DTM rendering

### ISSUE THREAD

**Issue by joa-quim** [avik-pal/RayTracer.jl#40]
Hi,

Could this package be used to create images like the one in this [GMT post](https://forum.generic-mapping-tools.org/t/true-lighting-in-gmt/983)

**Comment by avik-pal** [comment]
Hi @joa-quim,
(By a very superficial glance on the discussion) It seems to be possible. However, unless you want to compute gradients wrt something, I would **strongly** discourage using this package or any differentiable rendering package for that matter.

Also, I don't expect the package to work as expected in the latest julia release. I will work on fixing this but won't be able to do so until early next year.

**Comment by joa-quim** [comment]
Thanks, this was a exploratory thought for something I would like to do one day but which also low priority in my list.
I'll close this issue.
