### ISSUE TITLE
Zygote.forward Usage in RayTracer.jl/docs/src/inverse_lighting.md

### ISSUE THREAD

**Issue by umbriquse** [avik-pal/RayTracer.jl#47]
Hello, I going through some of your posted tutorials and I ran into a bug when using the Zygote.forward function (see below). I looked through some 0.4 and 0.5 versions of Zygote and couldn't find that function, so I am curious what that function is being used for. My current guess is that it's being used like the forwarddiff function in Zygote.

```
for i in 1:401
    loss, back_fn = Zygote.forward(light_guess) do L
        sum((render(L, scene) .- target_img) .^ 2)
    end
    @show loss
    gs = back_fn(1.0f0)
    update!(opt, light_guess.intensity, gs[1].intensity)
    update!(opt, light_guess.position, gs[1].position)
    if i % 5 == 1
        save("./results_inv_lighting/iteration_$i.png",
             showimg(zeroonenorm(render(light_guess, scene))))
    end
end
```

**Comment by avik-pal** [comment]
In the latest version of Zygote, it is `Zygote.pullback`
