### ISSUE TITLE
Mesh rendering

### ISSUE THREAD

**Issue by tejank10** [avik-pal/RayTracer.jl#5]
Following would be required to render a mesh. It is a `.obj` file. It contains vertex list and `.mtl` file to use for material. `.mtl` file contains path to the texture image to be used and some attributes. We can make an object like `pyglet.graphics.vertex_list` to store the vertices and its attributes. This object can later be used while rendering.

- [x] Getting texture from an image
- [x] Rendering arbitrary meshes (ie vertices) with given texture

**Comment by avik-pal** [comment]
Arbitrary Mesh Rendering is available in `ap/examples` branch. It is not efficient but a minimal working version.

**Comment by avik-pal** [comment]
This will be handled correctly once #8 is merged. Performance is still an issue but needs to be handled separately.
